### ISSUE TITLE
Thoughts on just having a single version of this going forward?

### ISSUE THREAD

**Issue by aminland** [a-x-/eslint-plugin-coffeescript#7]
@a-x- I think this is confusing for people that there are two different named things that are in different stages of development.

Since the idea here was to lint coffeescript, I ended up rewriting the whole thing in coffeescript (this way the thing itself could be used to lint itself). 

My company will be maintaining the @fellow namespaced npm repo (we're big coffeescript junkies), so I'd like to suggest we mark this repo as deprecated, and go forward with our rewritten version? 

I can grant you write access to the github in case you wanna make changes (also i'm pretty immediate about responding to PRs since I get emails about them)

Thoughts?

**Comment by a-x-** [comment]
Ok. Add readme notice please
